# Enable mouse support (click to select panes/windows)
set -g mouse on

# Use vi mode for copy mode (easier for vim users)
setw -g mode-keys vi

# Change prefix from Ctrl+b to Ctrl+a (like GNU screen)
set -g prefix C-q
unbind C-b
bind C-q send-prefix

# Reload config without restarting tmux: Ctrl+b then :
# type: source-file ~/.tmux.conf
set -g default-shell /bin/zsh
