#!/usr/bin/env bash

sudo dnf install -y git tldr

GIT_VERSION=$(git --version 2>&1)

echo "git version: $GIT_VERSION"

echo "1. Initializing git configurations..."
CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../config" && pwd)"
cp "$CONFIG_DIR/gitconfig" "$HOME/.gitconfig"

echo "2. Creating a ssh key for github..."
ssh-keygen -t ed25519 -C "abdulkasif.ra@gmail.com"

echo "3. Adding ssh key to ssh agent..."
eval "$(ssh-agent -s)"
ssh-add "$HOME/.ssh/id_ed25519"

echo "4. Copy the public key and paste it GitHub"
cat "$HOME/.ssh/id_ed25519.pub"
