#!/usr/bin/env bash

echo "Setting OneDark theme..."

THEME_DIR="$HOME/.config/nvim/lua/plugins"

mkdir -p "$THEME_DIR"

cat <<EOF >"$THEME_DIR/onedark.lua"
return {
    "navarasu/onedark.nvim",
    priority = 1000,
    config = function()
    -- Lua
    require('onedark').setup  {
        -- Main options --
        style = 'darker', -- Default theme style. Choose between 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer' and 'light'
        transparent = true,  -- Show/hide background
        term_colors = true, -- Change terminal color as per the selected theme style
        ending_tildes = false, -- Show the end-of-buffer tildes. By default they are hidden
        cmp_itemkind_reverse = false, -- reverse item kind highlights in cmp menu

        -- toggle theme style ---
        toggle_style_key = nil, -- keybind to toggle theme style. Leave it nil to disable it, or set it to a string, for example "<leader>ts"
        toggle_style_list = {'dark', 'darker', 'cool', 'deep', 'warm', 'warmer', 'light'}, -- List of styles to toggle between

        -- Change code style ---
        -- Options are italic, bold, underline, none
        -- You can configure multiple style with comma separated, For e.g., keywords = 'italic,bold'
        code_style = {
            comments = 'none',
            keywords = 'none',
            functions = 'bold',
            strings = 'none',
            variables = 'none'
        },

        -- Lualine options --
        lualine = {
            transparent = false, -- lualine center bar transparency
        },

        -- Custom Highlights --
        colors = {}, -- Override default colors
        highlights = {}, -- Override highlight groups

        -- Plugins Config --
        diagnostics = {
            darker = true, -- darker colors for diagnostic
            undercurl = true,   -- use undercurl instead of underline for diagnostics
            background = true,    -- use background color for virtual text
        },
    }
    require('onedark').load()
    end
}
EOF

cat <<EOF >"$THEME_DIR/neo-tree.lua"
return {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
        window = {
            width = 30
        },
    },
}
EOF

cat <<EOF >"$THEME_DIR/undotree.lua"
return {
  "mbbill/undotree",
  keys = {
    {
      "<leader>u",
      "<cmd>UndotreeToggle<CR>",
      desc = "Toggle Undotree",
    },
  },
  config = function()
    -- Optional: Add any specific setup options here if needed.
    -- For example, you can set the window position:
    vim.g.undotree_Position = "right"
    -- Or set the window size:
    vim.g.undotree_Shorten_Method = "cut"
  end,
}
EOF
echo "Run nvim to complete installation"
