#!/usr/bin/env bash

sudo dnf install -y vim fd ripgrep fzf gcc

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage

chmod u+x nvim-linux-x86_64.appimage

sudo mv nvim-linux-x86_64.appimage /usr/local/bin/nvim

NVIM_CONFIG="$HOME/.config/nvim"

echo "Installing LazyVim....."

git clone https://github.com/LazyVim/starter "$NVIM_CONFIG"

rm -rf "$NVIM_CONFIG/.git"

echo "Run nvim to complete the installation"
