#!/usr/bin/env bash

sudo rpm --import https://rpm.opera.com/rpmrepo.key

sudo tee /etc/yum.repos.d/opera.repo <<EOF
[opera]
name=Opera packages
type=rpm-md
baseurl=https://rpm.opera.com/rpm
gpgcheck=1
gpgkey=https://rpm.opera.com/rpmrepo.key
enabled=1
EOF

sudo dnf install -y opera-stable
