#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

. "$HOME/.cargo/env"

RUSTC_VERSION=$(rustc --version 2>&1)

echo "rustc version: $RUSTC_VERSION"

# Rust analyzer installation
rustup component add rust-analyzer

